services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: grant_workflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
